import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import CreateTodo from "../components/CreateTodo";
import ToDoList from "../components/ToDoList";
import styles from "../styles/Home.module.css";
import { auth, firestore, googleAuthprovider, postToJSON } from "../lib/firebase"
import { GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import { collectionGroup, getDocs, limit, orderBy, query } from "firebase/firestore";

/**
 * TODOs
 *  Create Users collection
 *  Create user doc if none exists already for this user
 *  Create Todos collection for each user
 *  Create each respective todo
 */
// Max todos to query per page
const LIMIT = 2;

export async function getServerSideProps() {
  const q = query(
    collectionGroup(firestore, "todos"),
    // where("published", "==", true),
    orderBy("createdAt", "desc"),
    limit(LIMIT)
  );

  const todos = (await getDocs(q)).docs.map(postToJSON);
  return {
    props: { todos }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const [user, setUser] = useState(auth?.currentUser)
  const [todos, setTodos] = useState(props.todos);

  async function signInToGoogle() {
    const person = await signInWithPopup(auth, googleAuthprovider);
    setUser(person.user)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user ?  <><ToDoList todos={todos}></ToDoList>
          <CreateTodo setTodos={setTodos}></CreateTodo></> : <button onClick={signInToGoogle}>Sign in with Google</button>}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
