import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import CreateTodo from "../components/CreateTodo";
import ToDoList from "../components/ToDoList";
import styles from "../styles/Home.module.css";
import {
  auth,
  firestore,
  googleAuthprovider,
  postToJSON,
} from "../lib/firebase";
import { GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import {
  collectionGroup,
  getDocs,
  limit,
  orderBy,
  query,
} from "firebase/firestore";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import {
  Avatar,
  Button,
  Container,
  CssBaseline,
  Typography,
} from "@mui/material";
import { Box } from "@mui/system";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";

/**
 * TODOs
 *  Create Users collection
 *  Create user doc if none exists already for this user
 *  Create Todos collection for each user
 *  Create each respective todo
 */
// Max todos to query per page
const LIMIT = 2;
const theme = createTheme();

export async function getServerSideProps() {
  const q = query(
    collectionGroup(firestore, "todos"),
    orderBy("createdAt", "desc"),
    limit(LIMIT)
  );

  const todos = (await getDocs(q)).docs.map(postToJSON);
  return {
    props: { todos }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const [user, setUser] = useState(auth?.currentUser);
  const [todos, setTodos] = useState(props.todos);

  async function signInToGoogle() {
    const person = await signInWithPopup(auth, googleAuthprovider);
    setUser(person.user);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user ? (
          <>
            <ToDoList todos={todos}></ToDoList>
            <CreateTodo setTodos={setTodos}></CreateTodo>
          </>
        ) : (
          <ThemeProvider theme={theme}>
            <Container component="main" maxWidth="xs">
              <CssBaseline />
              <Box
                sx={{
                  marginTop: 8,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                }}
              >
                <Avatar sx={{ m: 1, bgcolor: "secondary.main" }}>
                  <LockOutlinedIcon />
                </Avatar>
                <Typography component="h1" variant="h5">
                  Sign in
                </Typography>{" "}
                <Button
                  onClick={signInToGoogle}
                  type="submit"
                  fullWidth
                  variant="contained"
                  sx={{ mt: 3, mb: 2 }}
                >
                  Sign In With Google
                </Button>
              </Box>
            </Container>
          </ThemeProvider>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
